/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

let _persike_dsh_project_tools_docker_browseCompose_parameter_0$schema$value
const _persike_dsh_project_tools_docker_browseCompose_parameter_0$schema = () => (_persike_dsh_project_tools_docker_browseCompose_parameter_0$schema$value ??= z.object({
  'path': z.string().optional(),
}))
let _persike_dsh_project_tools_docker_browseCompose_result$schema$value
const _persike_dsh_project_tools_docker_browseCompose_result$schema = () => (_persike_dsh_project_tools_docker_browseCompose_result$schema$value ??= z.object({
  'path': z.string().readonly(),
  'home': z.string().readonly(),
  'crumbs': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'directory': z.boolean().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'directory': z.boolean().readonly(),
  'hidden': z.boolean().readonly(),
})).readonly(),
  'truncated': z.boolean().readonly(),
}))
let _persike_dsh_project_tools_docker_composeDown_parameter_0$schema$value
const _persike_dsh_project_tools_docker_composeDown_parameter_0$schema = () => (_persike_dsh_project_tools_docker_composeDown_parameter_0$schema$value ??= z.object({
  'file': z.string(),
  'project': z.string().optional(),
}))
let _persike_dsh_project_tools_docker_composeDown_result$schema$value
const _persike_dsh_project_tools_docker_composeDown_result$schema = () => (_persike_dsh_project_tools_docker_composeDown_result$schema$value ??= z.object({
  'project': z.string().readonly(),
  'output': z.string().readonly(),
  'containers': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'image': z.string().readonly(),
  'state': z.string().readonly(),
  'status': z.string().readonly(),
  'project': z.string().readonly().optional(),
  'service': z.string().readonly().optional(),
  'ports': z.array(z.string()).readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
}))
let _persike_dsh_project_tools_docker_composeUp_parameter_0$schema$value
const _persike_dsh_project_tools_docker_composeUp_parameter_0$schema = () => (_persike_dsh_project_tools_docker_composeUp_parameter_0$schema$value ??= z.object({
  'file': z.string(),
  'project': z.string().optional(),
}))
let _persike_dsh_project_tools_docker_composeUp_result$schema$value
const _persike_dsh_project_tools_docker_composeUp_result$schema = () => (_persike_dsh_project_tools_docker_composeUp_result$schema$value ??= z.object({
  'project': z.string().readonly(),
  'output': z.string().readonly(),
  'containers': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'image': z.string().readonly(),
  'state': z.string().readonly(),
  'status': z.string().readonly(),
  'project': z.string().readonly().optional(),
  'service': z.string().readonly().optional(),
  'ports': z.array(z.string()).readonly(),
  'createdAt': z.string().readonly(),
})).readonly(),
}))
let _persike_dsh_project_tools_docker_control_parameter_0$schema$value
const _persike_dsh_project_tools_docker_control_parameter_0$schema = () => (_persike_dsh_project_tools_docker_control_parameter_0$schema$value ??= z.object({
  'container': z.string(),
  'action': z.union([z.literal("start"), z.literal("stop"), z.literal("restart")]),
}))
let _persike_dsh_project_tools_docker_control_result$schema$value
const _persike_dsh_project_tools_docker_control_result$schema = () => (_persike_dsh_project_tools_docker_control_result$schema$value ??= z.object({
  'container': z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'image': z.string().readonly(),
  'state': z.string().readonly(),
  'status': z.string().readonly(),
  'project': z.string().readonly().optional(),
  'service': z.string().readonly().optional(),
  'ports': z.array(z.string()).readonly(),
  'createdAt': z.string().readonly(),
}),
}))
let _persike_dsh_project_tools_docker_engineStatus_parameter_0$schema$value
const _persike_dsh_project_tools_docker_engineStatus_parameter_0$schema = () => (_persike_dsh_project_tools_docker_engineStatus_parameter_0$schema$value ??= z.object({}))
let _persike_dsh_project_tools_docker_engineStatus_result$schema$value
const _persike_dsh_project_tools_docker_engineStatus_result$schema = () => (_persike_dsh_project_tools_docker_engineStatus_result$schema$value ??= z.object({
  'status': z.object({
  'running': z.boolean().readonly(),
  'startable': z.boolean().readonly(),
  'installable': z.boolean().readonly(),
  'runtime': z.string().readonly().optional(),
  'detail': z.string().readonly().optional(),
}),
}))
let _persike_dsh_project_tools_docker_installEngine_parameter_0$schema$value
const _persike_dsh_project_tools_docker_installEngine_parameter_0$schema = () => (_persike_dsh_project_tools_docker_installEngine_parameter_0$schema$value ??= z.object({}))
let _persike_dsh_project_tools_docker_installEngine_result$schema$value
const _persike_dsh_project_tools_docker_installEngine_result$schema = () => (_persike_dsh_project_tools_docker_installEngine_result$schema$value ??= z.object({
  'status': z.object({
  'running': z.boolean().readonly(),
  'startable': z.boolean().readonly(),
  'installable': z.boolean().readonly(),
  'runtime': z.string().readonly().optional(),
  'detail': z.string().readonly().optional(),
}),
  'output': z.string(),
}))
let _persike_dsh_project_tools_docker_listContainers_parameter_0$schema$value
const _persike_dsh_project_tools_docker_listContainers_parameter_0$schema = () => (_persike_dsh_project_tools_docker_listContainers_parameter_0$schema$value ??= z.object({
  'all': z.boolean().optional(),
  'project': z.string().optional(),
}))
let _persike_dsh_project_tools_docker_listContainers_result$schema$value
const _persike_dsh_project_tools_docker_listContainers_result$schema = () => (_persike_dsh_project_tools_docker_listContainers_result$schema$value ??= z.object({
  'containers': z.array(z.object({
  'id': z.string().readonly(),
  'name': z.string().readonly(),
  'image': z.string().readonly(),
  'state': z.string().readonly(),
  'status': z.string().readonly(),
  'project': z.string().readonly().optional(),
  'service': z.string().readonly().optional(),
  'ports': z.array(z.string()).readonly(),
  'createdAt': z.string().readonly(),
})),
}))
let _persike_dsh_project_tools_docker_listImages_parameter_0$schema$value
const _persike_dsh_project_tools_docker_listImages_parameter_0$schema = () => (_persike_dsh_project_tools_docker_listImages_parameter_0$schema$value ??= z.object({}))
let _persike_dsh_project_tools_docker_listImages_result$schema$value
const _persike_dsh_project_tools_docker_listImages_result$schema = () => (_persike_dsh_project_tools_docker_listImages_result$schema$value ??= z.object({
  'images': z.array(z.object({
  'id': z.string().readonly(),
  'tags': z.array(z.string()).readonly(),
  'size': z.number().readonly(),
  'createdAt': z.string().readonly(),
})),
}))
let _persike_dsh_project_tools_docker_logs_parameter_0$schema$value
const _persike_dsh_project_tools_docker_logs_parameter_0$schema = () => (_persike_dsh_project_tools_docker_logs_parameter_0$schema$value ??= z.object({
  'container': z.string(),
  'tail': z.number().optional(),
}))
let _persike_dsh_project_tools_docker_logs_result$schema$value
const _persike_dsh_project_tools_docker_logs_result$schema = () => (_persike_dsh_project_tools_docker_logs_result$schema$value ??= z.object({
  'container': z.string(),
  'content': z.string(),
  'truncated': z.boolean(),
}))
let _persike_dsh_project_tools_docker_removeContainer_parameter_0$schema$value
const _persike_dsh_project_tools_docker_removeContainer_parameter_0$schema = () => (_persike_dsh_project_tools_docker_removeContainer_parameter_0$schema$value ??= z.object({
  'container': z.string(),
  'force': z.boolean().optional(),
}))
let _persike_dsh_project_tools_docker_removeContainer_result$schema$value
const _persike_dsh_project_tools_docker_removeContainer_result$schema = () => (_persike_dsh_project_tools_docker_removeContainer_result$schema$value ??= z.object({
  'container': z.string(),
}))
let _persike_dsh_project_tools_docker_removeImage_parameter_0$schema$value
const _persike_dsh_project_tools_docker_removeImage_parameter_0$schema = () => (_persike_dsh_project_tools_docker_removeImage_parameter_0$schema$value ??= z.object({
  'image': z.string(),
  'force': z.boolean().optional(),
}))
let _persike_dsh_project_tools_docker_removeImage_result$schema$value
const _persike_dsh_project_tools_docker_removeImage_result$schema = () => (_persike_dsh_project_tools_docker_removeImage_result$schema$value ??= z.object({
  'image': z.string(),
}))
let _persike_dsh_project_tools_docker_startEngine_parameter_0$schema$value
const _persike_dsh_project_tools_docker_startEngine_parameter_0$schema = () => (_persike_dsh_project_tools_docker_startEngine_parameter_0$schema$value ??= z.object({}))
let _persike_dsh_project_tools_docker_startEngine_result$schema$value
const _persike_dsh_project_tools_docker_startEngine_result$schema = () => (_persike_dsh_project_tools_docker_startEngine_result$schema$value ??= z.object({
  'status': z.object({
  'running': z.boolean().readonly(),
  'startable': z.boolean().readonly(),
  'installable': z.boolean().readonly(),
  'runtime': z.string().readonly().optional(),
  'detail': z.string().readonly().optional(),
}),
  'output': z.string(),
}))
let _persike_dsh_project_tools_editor_languageServers_parameter_0$schema$value
const _persike_dsh_project_tools_editor_languageServers_parameter_0$schema = () => (_persike_dsh_project_tools_editor_languageServers_parameter_0$schema$value ??= z.object({}))
let _persike_dsh_project_tools_editor_languageServers_result$schema$value
const _persike_dsh_project_tools_editor_languageServers_result$schema = () => (_persike_dsh_project_tools_editor_languageServers_result$schema$value ??= z.object({
  'servers': z.array(z.object({
  'id': z.string().readonly(),
  'extensions': z.array(z.string()).readonly(),
})),
}))
let _persike_dsh_project_tools_editor_listDir_parameter_0$schema$value
const _persike_dsh_project_tools_editor_listDir_parameter_0$schema = () => (_persike_dsh_project_tools_editor_listDir_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).optional(),
  'path': z.string().optional(),
}))
let _persike_dsh_project_tools_editor_listDir_result$schema$value
const _persike_dsh_project_tools_editor_listDir_result$schema = () => (_persike_dsh_project_tools_editor_listDir_result$schema$value ??= z.object({
  'path': z.string().readonly(),
  'root': z.string().readonly(),
  'entries': z.array(z.object({
  'name': z.string().readonly(),
  'path': z.string().readonly(),
  'directory': z.boolean().readonly(),
})).readonly(),
}))
let _persike_dsh_project_tools_editor_readFile_parameter_0$schema$value
const _persike_dsh_project_tools_editor_readFile_parameter_0$schema = () => (_persike_dsh_project_tools_editor_readFile_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).optional(),
  'path': z.string(),
}))
let _persike_dsh_project_tools_editor_readFile_result$schema$value
const _persike_dsh_project_tools_editor_readFile_result$schema = () => (_persike_dsh_project_tools_editor_readFile_result$schema$value ??= z.object({
  'path': z.string().readonly(),
  'content': z.string().readonly(),
  'version': z.string().readonly(),
}))
let _persike_dsh_project_tools_treadmill_describe_parameter_0$schema$value
const _persike_dsh_project_tools_treadmill_describe_parameter_0$schema = () => (_persike_dsh_project_tools_treadmill_describe_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).optional(),
}))
let _persike_dsh_project_tools_treadmill_describe_result$schema$value
const _persike_dsh_project_tools_treadmill_describe_result$schema = () => (_persike_dsh_project_tools_treadmill_describe_result$schema$value ??= z.object({
  'root': z.string().readonly(),
  'enabled': z.boolean().readonly(),
  'tableSource': z.union([z.literal("project"), z.literal("global")]).readonly(),
  'stages': z.array(z.object({
  'requires': z.array(z.string()).readonly().optional(),
  'id': z.string().readonly(),
  'label': z.string().readonly(),
  'section': z.string().readonly(),
  'skill': z.string().readonly(),
  'args': z.string().readonly().optional(),
  'gate': z.union([z.literal("manual"), z.literal("auto")]).readonly(),
  'verdict': z.boolean().readonly(),
  'produces': z.array(z.string()).readonly(),
  'enabled': z.boolean().readonly(),
})).readonly(),
  'pipelineError': z.string().readonly().optional(),
  'files': z.array(z.object({
  'path': z.string().readonly(),
  'category': z.string().readonly(),
  'size': z.number().readonly(),
})).readonly(),
}))
let _persike_dsh_project_tools_treadmill_readFile_parameter_0$schema$value
const _persike_dsh_project_tools_treadmill_readFile_parameter_0$schema = () => (_persike_dsh_project_tools_treadmill_readFile_parameter_0$schema$value ??= z.object({
  'path': z.string(),
}))
let _persike_dsh_project_tools_treadmill_readFile_result$schema$value
const _persike_dsh_project_tools_treadmill_readFile_result$schema = () => (_persike_dsh_project_tools_treadmill_readFile_result$schema$value ??= z.object({
  'path': z.string(),
  'content': z.string(),
}))
let _persike_dsh_project_tools_treadmill_saveToProject_parameter_0$schema$value
const _persike_dsh_project_tools_treadmill_saveToProject_parameter_0$schema = () => (_persike_dsh_project_tools_treadmill_saveToProject_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()),
  'path': z.string(),
  'content': z.string(),
}))
let _persike_dsh_project_tools_treadmill_saveToProject_result$schema$value
const _persike_dsh_project_tools_treadmill_saveToProject_result$schema = () => (_persike_dsh_project_tools_treadmill_saveToProject_result$schema$value ??= z.object({
  'path': z.string(),
}))
let _persike_dsh_project_tools_treadmill_updateStage_parameter_0$schema$value
const _persike_dsh_project_tools_treadmill_updateStage_parameter_0$schema = () => (_persike_dsh_project_tools_treadmill_updateStage_parameter_0$schema$value ??= z.object({
  'sessionId': z.intersection(z.string(), z.unknown()).optional(),
  'id': z.string(),
  'enabled': z.boolean().optional(),
  'gate': z.union([z.literal("manual"), z.literal("auto")]).optional(),
}))
let _persike_dsh_project_tools_treadmill_updateStage_result$schema$value
const _persike_dsh_project_tools_treadmill_updateStage_result$schema = () => (_persike_dsh_project_tools_treadmill_updateStage_result$schema$value ??= z.object({
  'id': z.string(),
  'tableSource': z.union([z.literal("project"), z.literal("global")]),
}))
let _persike_dsh_project_tools_treadmill_writeFile_parameter_0$schema$value
const _persike_dsh_project_tools_treadmill_writeFile_parameter_0$schema = () => (_persike_dsh_project_tools_treadmill_writeFile_parameter_0$schema$value ??= z.object({
  'path': z.string(),
  'content': z.string(),
}))
let _persike_dsh_project_tools_treadmill_writeFile_result$schema$value
const _persike_dsh_project_tools_treadmill_writeFile_result$schema = () => (_persike_dsh_project_tools_treadmill_writeFile_result$schema$value ??= z.object({
  'path': z.string(),
}))

export const TYPERT = {
  package: '@persike/dsh-project-tools',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@persike/dsh-project-tools#docker/browseCompose',
      service: 'dockerController',
      namespace: 'docker',
      method: 'browseCompose',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerBrowseComposeRequest',
            create: _persike_dsh_project_tools_docker_browseCompose_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerBrowseComposeValue',
        create: _persike_dsh_project_tools_docker_browseCompose_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":226,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/composeDown',
      service: 'dockerController',
      namespace: 'docker',
      method: 'composeDown',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerComposeDownRequest',
            create: _persike_dsh_project_tools_docker_composeDown_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerComposeDownValue',
        create: _persike_dsh_project_tools_docker_composeDown_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":295,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/composeUp',
      service: 'dockerController',
      namespace: 'docker',
      method: 'composeUp',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerComposeUpRequest',
            create: _persike_dsh_project_tools_docker_composeUp_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerComposeUpValue',
        create: _persike_dsh_project_tools_docker_composeUp_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":264,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/control',
      service: 'dockerController',
      namespace: 'docker',
      method: 'control',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerControlRequest',
            create: _persike_dsh_project_tools_docker_control_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerControlValue',
        create: _persike_dsh_project_tools_docker_control_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":116,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/engineStatus',
      service: 'dockerController',
      namespace: 'docker',
      method: 'engineStatus',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerEngineStatusRequest',
            create: _persike_dsh_project_tools_docker_engineStatus_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerEngineStatusValue',
        create: _persike_dsh_project_tools_docker_engineStatus_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":29,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/installEngine',
      service: 'dockerController',
      namespace: 'docker',
      method: 'installEngine',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerInstallEngineRequest',
            create: _persike_dsh_project_tools_docker_installEngine_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerInstallEngineValue',
        create: _persike_dsh_project_tools_docker_installEngine_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":74,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/listContainers',
      service: 'dockerController',
      namespace: 'docker',
      method: 'listContainers',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerListContainersRequest',
            create: _persike_dsh_project_tools_docker_listContainers_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerListContainersValue',
        create: _persike_dsh_project_tools_docker_listContainers_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":93,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/listImages',
      service: 'dockerController',
      namespace: 'docker',
      method: 'listImages',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerListImagesRequest',
            create: _persike_dsh_project_tools_docker_listImages_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerListImagesValue',
        create: _persike_dsh_project_tools_docker_listImages_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":176,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/logs',
      service: 'dockerController',
      namespace: 'docker',
      method: 'logs',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerLogsRequest',
            create: _persike_dsh_project_tools_docker_logs_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerLogsValue',
        create: _persike_dsh_project_tools_docker_logs_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":195,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/removeContainer',
      service: 'dockerController',
      namespace: 'docker',
      method: 'removeContainer',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerRemoveContainerRequest',
            create: _persike_dsh_project_tools_docker_removeContainer_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerRemoveContainerValue',
        create: _persike_dsh_project_tools_docker_removeContainer_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":136,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/removeImage',
      service: 'dockerController',
      namespace: 'docker',
      method: 'removeImage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerRemoveImageRequest',
            create: _persike_dsh_project_tools_docker_removeImage_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerRemoveImageValue',
        create: _persike_dsh_project_tools_docker_removeImage_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":156,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#docker/startEngine',
      service: 'dockerController',
      namespace: 'docker',
      method: 'startEngine',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#DockerStartEngineRequest',
            create: _persike_dsh_project_tools_docker_startEngine_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#DockerStartEngineValue',
        create: _persike_dsh_project_tools_docker_startEngine_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/docker.ts","line":55,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#editor/languageServers',
      service: 'editorController',
      namespace: 'editor',
      method: 'languageServers',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#EditorLanguageServersRequest',
            create: _persike_dsh_project_tools_editor_languageServers_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#EditorLanguageServersValue',
        create: _persike_dsh_project_tools_editor_languageServers_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/editor.ts","line":24,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#editor/listDir',
      service: 'editorController',
      namespace: 'editor',
      method: 'listDir',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#EditorListDirRequest',
            create: _persike_dsh_project_tools_editor_listDir_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#EditorListDirValue',
        create: _persike_dsh_project_tools_editor_listDir_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/editor.ts","line":42,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#editor/readFile',
      service: 'editorController',
      namespace: 'editor',
      method: 'readFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#EditorReadFileRequest',
            create: _persike_dsh_project_tools_editor_readFile_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#EditorReadFileValue',
        create: _persike_dsh_project_tools_editor_readFile_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/editor.ts","line":78,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#treadmill/describe',
      service: 'treadmillController',
      namespace: 'treadmill',
      method: 'describe',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#TreadmillDescribeRequest',
            create: _persike_dsh_project_tools_treadmill_describe_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#TreadmillDescribeValue',
        create: _persike_dsh_project_tools_treadmill_describe_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/treadmill.ts","line":24,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#treadmill/readFile',
      service: 'treadmillController',
      namespace: 'treadmill',
      method: 'readFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#TreadmillReadFileRequest',
            create: _persike_dsh_project_tools_treadmill_readFile_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#TreadmillReadFileValue',
        create: _persike_dsh_project_tools_treadmill_readFile_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/treadmill.ts","line":50,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#treadmill/saveToProject',
      service: 'treadmillController',
      namespace: 'treadmill',
      method: 'saveToProject',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#TreadmillSaveToProjectRequest',
            create: _persike_dsh_project_tools_treadmill_saveToProject_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#TreadmillSaveToProjectValue',
        create: _persike_dsh_project_tools_treadmill_saveToProject_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/treadmill.ts","line":121,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#treadmill/updateStage',
      service: 'treadmillController',
      namespace: 'treadmill',
      method: 'updateStage',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#TreadmillUpdateStageRequest',
            create: _persike_dsh_project_tools_treadmill_updateStage_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#TreadmillUpdateStageValue',
        create: _persike_dsh_project_tools_treadmill_updateStage_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/treadmill.ts","line":87,"column":9},
    },
    {
      id: '@persike/dsh-project-tools#treadmill/writeFile',
      service: 'treadmillController',
      namespace: 'treadmill',
      method: 'writeFile',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@persike/dsh-project-tools/types#TreadmillWriteFileRequest',
            create: _persike_dsh_project_tools_treadmill_writeFile_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@persike/dsh-project-tools/types#TreadmillWriteFileValue',
        create: _persike_dsh_project_tools_treadmill_writeFile_result$schema,
      },
      sourceLocation: {"file":"packages/project-tools/src/treadmill.ts","line":68,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "The Docker access service, registered as `ctx.docker` (one instance per context). Selection semantics, resolved at execution time and never order-dependent: - A configured id that is registered and `available()` → that provider. - A configured id not registered → `DOCKER_PROVIDER_CONFIGURED_MISSING`. - A configured id registered but unavailable → `DOCKER_PROVIDER_CONFIGURED_UNAVAILABLE`. - No id configured, exactly one registered usable provider → that provider. - No id configured, several usable providers → `DOCKER_PROVIDER_AMBIGUOUS`. - No id configured, no usable provider → `DOCKER_PROVIDER_UNAVAILABLE`.",
        "summary": "The Docker access service, registered as `ctx.docker` (one instance per context).",
        "tags": [],
        "jsDoc": "/**\n * The Docker access service, registered as `ctx.docker` (one instance per\n * context).\n *\n * Selection semantics, resolved at execution time and never order-dependent:\n * - A configured id that is registered and `available()` → that provider.\n * - A configured id not registered → `DOCKER_PROVIDER_CONFIGURED_MISSING`.\n * - A configured id registered but unavailable → `DOCKER_PROVIDER_CONFIGURED_UNAVAILABLE`.\n * - No id configured, exactly one registered usable provider → that provider.\n * - No id configured, several usable providers → `DOCKER_PROVIDER_AMBIGUOUS`.\n * - No id configured, no usable provider → `DOCKER_PROVIDER_UNAVAILABLE`.\n */",
        "key": "docker",
        "exportName": "DockerRuntime",
        "members": [
          {
            "kind": "method",
            "name": "registerProvider",
            "signature": "registerProvider(provider: DockerProvider): () => void",
            "summary": "Register one container backend.",
            "jsDoc": "/**\n * Register one container backend.\n * @param provider - the backend to add.\n * @returns a disposer that removes it; runs with the calling fiber.\n */"
          },
          {
            "kind": "method",
            "name": "providerIds",
            "signature": "providerIds(): readonly string[]",
            "summary": "Ids of every registered backend, in registration order.",
            "jsDoc": "/**\n * Ids of every registered backend, in registration order. Selection never\n * consults this order; it exists for diagnostics and for the UI's provider\n * display.\n * @returns the registered provider ids.\n */"
          },
          {
            "kind": "method",
            "name": "engineStatus",
            "signature": "async engineStatus(signal?: AbortSignal): Promise<DockerEngineStatus>",
            "summary": "Report whether an engine is reachable and what can be done about it.",
            "jsDoc": "/**\n * Report whether an engine is reachable and what can be done about it. A\n * composition whose backends cannot manage an engine answers a status with\n * every capability false, never an error: the absence of the capability is\n * itself the answer a UI renders.\n * @param signal - cancellation for the underlying probe.\n * @returns the engine status.\n */"
          },
          {
            "kind": "method",
            "name": "startEngine",
            "signature": "async startEngine(signal?: AbortSignal): Promise<DockerEngineResult>",
            "summary": "Start the local container runtime.",
            "jsDoc": "/**\n * Start the local container runtime.\n * @param signal - cancellation for the underlying command.\n * @returns the settled status and the command output.\n * @throws {DockerError} `DOCKER_ENGINE_UNMANAGEABLE` when no backend can start one.\n */"
          },
          {
            "kind": "method",
            "name": "installEngine",
            "signature": "async installEngine(signal?: AbortSignal): Promise<DockerEngineResult>",
            "summary": "Install a container runtime on this machine.",
            "jsDoc": "/**\n * Install a container runtime on this machine.\n * @param signal - cancellation for the underlying command.\n * @returns the settled status and the command output.\n * @throws {DockerError} `DOCKER_ENGINE_UNMANAGEABLE` when no backend can install one.\n */"
          },
          {
            "kind": "method",
            "name": "list",
            "signature": "async list(request: DockerListRequest = {}, signal?: AbortSignal): Promise<readonly DockerContainer[]>",
            "summary": "List containers on the selected backend.",
            "jsDoc": "/**\n * List containers on the selected backend.\n * @param request - listing filters.\n * @param signal - cancellation for the engine call.\n * @returns the matching containers.\n */"
          },
          {
            "kind": "method",
            "name": "control",
            "signature": "async control(request: DockerControlRequest, signal?: AbortSignal): Promise<DockerContainer>",
            "summary": "Apply one lifecycle action to a single container on the selected backend.",
            "jsDoc": "/**\n * Apply one lifecycle action to a single container on the selected backend.\n * @param request - the container and the action to apply.\n * @param signal - cancellation for the engine call.\n * @returns the container's state after the action settled.\n */"
          },
          {
            "kind": "method",
            "name": "removeContainer",
            "signature": "async removeContainer(request: DockerRemoveContainerRequest, signal?: AbortSignal): Promise<void>",
            "summary": "Remove one container from the selected backend.",
            "jsDoc": "/**\n * Remove one container from the selected backend. A backend without the\n * capability raises rather than reporting a removal that never happened.\n * @param request - the container to remove and whether to force it.\n * @param signal - cancellation for the engine call.\n * @returns nothing; the caller re-reads the listing.\n */"
          },
          {
            "kind": "method",
            "name": "removeImage",
            "signature": "async removeImage(request: DockerRemoveImageRequest, signal?: AbortSignal): Promise<void>",
            "summary": "Remove one locally stored image from the selected backend.",
            "jsDoc": "/**\n * Remove one locally stored image from the selected backend.\n * @param request - the image to remove and whether to force it.\n * @param signal - cancellation for the engine call.\n * @returns nothing; the caller re-reads the listing.\n */"
          },
          {
            "kind": "method",
            "name": "images",
            "signature": "async images(signal?: AbortSignal): Promise<readonly DockerImage[]>",
            "summary": "List locally available images on the selected backend.",
            "jsDoc": "/**\n * List locally available images on the selected backend.\n * @param signal - cancellation for the engine call.\n * @returns the local images.\n */"
          },
          {
            "kind": "method",
            "name": "logs",
            "signature": "async logs(request: DockerLogsRequest, signal?: AbortSignal): Promise<DockerLogsResult>",
            "summary": "Read one container's logs from the selected backend.",
            "jsDoc": "/**\n * Read one container's logs from the selected backend.\n * @param request - container and range to read.\n * @param signal - cancellation for the engine call.\n * @returns the collected log text.\n */"
          },
          {
            "kind": "method",
            "name": "composeUp",
            "signature": "async composeUp(request: DockerComposeRequest, signal?: AbortSignal): Promise<DockerComposeResult>",
            "summary": "Start a Compose project on the selected backend.",
            "jsDoc": "/**\n * Start a Compose project on the selected backend.\n * @param request - compose file, project, and service selection.\n * @param signal - cancellation for the engine call.\n * @returns the settled project state.\n */"
          },
          {
            "kind": "method",
            "name": "composeDown",
            "signature": "async composeDown(request: DockerComposeRequest, signal?: AbortSignal): Promise<DockerComposeResult>",
            "summary": "Stop and remove a Compose project's containers on the selected backend.",
            "jsDoc": "/**\n * Stop and remove a Compose project's containers on the selected backend.\n * @param request - compose file, project, and service selection.\n * @param signal - cancellation for the engine call.\n * @returns the settled project state.\n */"
          }
        ],
        "types": [
          {
            "name": "DockerComposeRequest",
            "declaration": "export interface DockerComposeRequest {\n    readonly file: string;\n    readonly project?: string;\n    readonly services?: readonly string[];\n}"
          },
          {
            "name": "DockerComposeResult",
            "declaration": "export interface DockerComposeResult {\n    readonly project: string;\n    readonly output: string;\n    readonly containers: readonly DockerContainer[];\n}"
          },
          {
            "name": "DockerContainer",
            "declaration": "export interface DockerContainer {\n    readonly id: string;\n    readonly name: string;\n    readonly image: string;\n    readonly state: DockerContainerState;\n    readonly status: string;\n    readonly project?: string;\n    readonly service?: string;\n    readonly ports: readonly string[];\n    readonly createdAt: string;\n}"
          },
          {
            "name": "DockerContainerState",
            "declaration": "export type DockerContainerState = 'created' | 'running' | 'paused' | 'restarting' | 'exited' | 'dead';"
          },
          {
            "name": "DockerControlAction",
            "declaration": "export type DockerControlAction = 'start' | 'stop' | 'restart';"
          },
          {
            "name": "DockerControlRequest",
            "declaration": "export interface DockerControlRequest {\n    readonly container: string;\n    readonly action: DockerControlAction;\n}"
          },
          {
            "name": "DockerEngineResult",
            "declaration": "export interface DockerEngineResult {\n    readonly status: DockerEngineStatus;\n    readonly output: string;\n}"
          },
          {
            "name": "DockerEngineStatus",
            "declaration": "export interface DockerEngineStatus {\n    readonly running: boolean;\n    readonly startable: boolean;\n    readonly installable: boolean;\n    readonly runtime?: string;\n    readonly detail?: string;\n}"
          },
          {
            "name": "DockerImage",
            "declaration": "export interface DockerImage {\n    readonly id: string;\n    readonly tags: readonly string[];\n    readonly size: number;\n    readonly createdAt: string;\n}"
          },
          {
            "name": "DockerListRequest",
            "declaration": "export interface DockerListRequest {\n    readonly all?: boolean;\n    readonly project?: string;\n}"
          },
          {
            "name": "DockerLogsRequest",
            "declaration": "export interface DockerLogsRequest {\n    readonly container: string;\n    readonly tail?: number;\n    readonly since?: string;\n}"
          },
          {
            "name": "DockerLogsResult",
            "declaration": "export interface DockerLogsResult {\n    readonly container: string;\n    readonly content: string;\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "DockerProvider",
            "declaration": "export interface DockerProvider {\n    readonly id: string;\n    available: () => Promise<boolean>;\n    engineStatus?: (signal?: AbortSignal) => Promise<DockerEngineStatus>;\n    startEngine?: (signal?: AbortSignal) => Promise<DockerEngineResult>;\n    installEngine?: (signal?: AbortSignal) => Promise<DockerEngineResult>;\n    list: (request: DockerListRequest, signal?: AbortSignal) => Promise<readonly DockerContainer[]>;\n    control: (request: DockerControlRequest, signal?: AbortSignal) => Promise<DockerContainer>;\n    removeContainer?: (request: DockerRemoveContainerRequest, signal?: AbortSignal) => Promise<void>;\n    removeImage?: (request: DockerRemoveImageRequest, signal?: AbortSignal) => Promise<void>;\n    images: (signal?: AbortSignal) => Promise<readonly DockerImage[]>;\n    logs: (request: DockerLogsRequest, signal?: AbortSignal) => Promise<DockerLogsResult>;\n    composeUp: (request: DockerComposeRequest, signal?: AbortSignal) => Promise<DockerComposeResult>;\n    composeDown: (request: DockerComposeRequest, signal?: AbortSignal) => Promise<DockerComposeResult>;\n}"
          },
          {
            "name": "DockerRemoveContainerRequest",
            "declaration": "export interface DockerRemoveContainerRequest {\n    readonly container: string;\n    readonly force?: boolean;\n}"
          },
          {
            "name": "DockerRemoveImageRequest",
            "declaration": "export interface DockerRemoveImageRequest {\n    readonly image: string;\n    readonly force?: boolean;\n}"
          }
        ]
      },
      {
        "description": "docker Remote owner.",
        "summary": "docker Remote owner.",
        "tags": [],
        "jsDoc": "/** docker Remote owner. */",
        "key": "dockerController",
        "exportName": "DockerController",
        "members": [
          {
            "kind": "method",
            "name": "engineStatus",
            "signature": "@Remote async engineStatus(request: DockerEngineStatusRequest, signal: AbortSignal): Promise<DockerEngineStatusValue>",
            "summary": "Execute docker.engineStatus.",
            "jsDoc": "/** Execute docker.engineStatus.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "startEngine",
            "signature": "@Remote async startEngine(request: DockerStartEngineRequest, signal: AbortSignal): Promise<DockerStartEngineValue>",
            "summary": "Execute docker.startEngine.",
            "jsDoc": "/** Execute docker.startEngine.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "installEngine",
            "signature": "@Remote async installEngine(request: DockerInstallEngineRequest, signal: AbortSignal): Promise<DockerInstallEngineValue>",
            "summary": "Execute docker.installEngine.",
            "jsDoc": "/** Execute docker.installEngine.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "listContainers",
            "signature": "@Remote async listContainers(request: DockerListContainersRequest, signal: AbortSignal): Promise<DockerListContainersValue>",
            "summary": "Execute docker.listContainers.",
            "jsDoc": "/** Execute docker.listContainers.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "control",
            "signature": "@Remote async control(request: DockerControlRequest, signal: AbortSignal): Promise<DockerControlValue>",
            "summary": "Execute docker.control.",
            "jsDoc": "/** Execute docker.control.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "removeContainer",
            "signature": "@Remote async removeContainer(request: DockerRemoveContainerRequest, signal: AbortSignal): Promise<DockerRemoveContainerValue>",
            "summary": "Execute docker.removeContainer.",
            "jsDoc": "/** Execute docker.removeContainer.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "removeImage",
            "signature": "@Remote async removeImage(request: DockerRemoveImageRequest, signal: AbortSignal): Promise<DockerRemoveImageValue>",
            "summary": "Execute docker.removeImage.",
            "jsDoc": "/** Execute docker.removeImage.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "listImages",
            "signature": "@Remote async listImages(request: DockerListImagesRequest, signal: AbortSignal): Promise<DockerListImagesValue>",
            "summary": "Execute docker.listImages.",
            "jsDoc": "/** Execute docker.listImages.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "logs",
            "signature": "@Remote async logs(request: DockerLogsRequest, signal: AbortSignal): Promise<DockerLogsValue>",
            "summary": "Execute docker.logs.",
            "jsDoc": "/** Execute docker.logs.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "browseCompose",
            "signature": "@Remote async browseCompose(request: DockerBrowseComposeRequest, signal: AbortSignal): Promise<DockerBrowseComposeValue>",
            "summary": "Execute docker.browseCompose.",
            "jsDoc": "/** Execute docker.browseCompose.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "composeUp",
            "signature": "@Remote async composeUp(request: DockerComposeUpRequest, signal: AbortSignal): Promise<DockerComposeUpValue>",
            "summary": "Execute docker.composeUp.",
            "jsDoc": "/** Execute docker.composeUp.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          },
          {
            "kind": "method",
            "name": "composeDown",
            "signature": "@Remote async composeDown(request: DockerComposeDownRequest, signal: AbortSignal): Promise<DockerComposeDownValue>",
            "summary": "Execute docker.composeDown.",
            "jsDoc": "/** Execute docker.composeDown.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled docker result.\n */"
          }
        ],
        "types": [
          {
            "name": "DockerBrowseComposeRequest",
            "declaration": "export type DockerBrowseComposeRequest = { path?: string; };"
          },
          {
            "name": "DockerBrowseComposeValue",
            "declaration": "export type DockerBrowseComposeValue = DockerComposeBrowse;"
          },
          {
            "name": "DockerComposeBrowse",
            "declaration": "export interface DockerComposeBrowse {\n    readonly path: string;\n    readonly home: string;\n    readonly crumbs: readonly DockerComposeBrowseEntry[];\n    readonly entries: readonly DockerComposeBrowseEntry[];\n    readonly truncated: boolean;\n}"
          },
          {
            "name": "DockerComposeBrowseEntry",
            "declaration": "export interface DockerComposeBrowseEntry {\n    readonly name: string;\n    readonly path: string;\n    readonly directory: boolean;\n    readonly hidden: boolean;\n}"
          },
          {
            "name": "DockerComposeDownRequest",
            "declaration": "export type DockerComposeDownRequest = { file: string; project?: string; };"
          },
          {
            "name": "DockerComposeDownValue",
            "declaration": "export type DockerComposeDownValue = DockerComposeOutcome;"
          },
          {
            "name": "DockerComposeOutcome",
            "declaration": "export interface DockerComposeOutcome {\n    readonly project: string;\n    readonly output: string;\n    readonly containers: readonly DockerContainerEntry[];\n}"
          },
          {
            "name": "DockerComposeUpRequest",
            "declaration": "export type DockerComposeUpRequest = { file: string; project?: string; };"
          },
          {
            "name": "DockerComposeUpValue",
            "declaration": "export type DockerComposeUpValue = DockerComposeOutcome;"
          },
          {
            "name": "DockerContainerEntry",
            "declaration": "export interface DockerContainerEntry {\n    readonly id: string;\n    readonly name: string;\n    readonly image: string;\n    readonly state: string;\n    readonly status: string;\n    readonly project?: string;\n    readonly service?: string;\n    readonly ports: readonly string[];\n    readonly createdAt: string;\n}"
          },
          {
            "name": "DockerControlRequest",
            "declaration": "export type DockerControlRequest = { container: string; action: 'start' | 'stop' | 'restart'; };"
          },
          {
            "name": "DockerControlValue",
            "declaration": "export type DockerControlValue = { container: DockerContainerEntry; };"
          },
          {
            "name": "DockerEngineStatusRequest",
            "declaration": "export type DockerEngineStatusRequest = {};"
          },
          {
            "name": "DockerEngineStatusValue",
            "declaration": "export type DockerEngineStatusValue = { status: DockerEngineStatusView; };"
          },
          {
            "name": "DockerEngineStatusView",
            "declaration": "export interface DockerEngineStatusView {\n    readonly running: boolean;\n    readonly startable: boolean;\n    readonly installable: boolean;\n    readonly runtime?: string;\n    readonly detail?: string;\n}"
          },
          {
            "name": "DockerImageEntry",
            "declaration": "export interface DockerImageEntry {\n    readonly id: string;\n    readonly tags: readonly string[];\n    readonly size: number;\n    readonly createdAt: string;\n}"
          },
          {
            "name": "DockerInstallEngineRequest",
            "declaration": "export type DockerInstallEngineRequest = {};"
          },
          {
            "name": "DockerInstallEngineValue",
            "declaration": "export type DockerInstallEngineValue = { status: DockerEngineStatusView; output: string; };"
          },
          {
            "name": "DockerListContainersRequest",
            "declaration": "export type DockerListContainersRequest = { all?: boolean; project?: string; };"
          },
          {
            "name": "DockerListContainersValue",
            "declaration": "export type DockerListContainersValue = { containers: readonly DockerContainerEntry[]; };"
          },
          {
            "name": "DockerListImagesRequest",
            "declaration": "export type DockerListImagesRequest = {};"
          },
          {
            "name": "DockerListImagesValue",
            "declaration": "export type DockerListImagesValue = { images: readonly DockerImageEntry[]; };"
          },
          {
            "name": "DockerLogsRequest",
            "declaration": "export type DockerLogsRequest = { container: string; tail?: number; };"
          },
          {
            "name": "DockerLogsValue",
            "declaration": "export type DockerLogsValue = { container: string; content: string; truncated: boolean; };"
          },
          {
            "name": "DockerRemoveContainerRequest",
            "declaration": "export type DockerRemoveContainerRequest = { container: string; force?: boolean; };"
          },
          {
            "name": "DockerRemoveContainerValue",
            "declaration": "export type DockerRemoveContainerValue = { container: string; };"
          },
          {
            "name": "DockerRemoveImageRequest",
            "declaration": "export type DockerRemoveImageRequest = { image: string; force?: boolean; };"
          },
          {
            "name": "DockerRemoveImageValue",
            "declaration": "export type DockerRemoveImageValue = { image: string; };"
          },
          {
            "name": "DockerStartEngineRequest",
            "declaration": "export type DockerStartEngineRequest = {};"
          },
          {
            "name": "DockerStartEngineValue",
            "declaration": "export type DockerStartEngineValue = { status: DockerEngineStatusView; output: string; };"
          }
        ]
      },
      {
        "description": "editor Remote owner.",
        "summary": "editor Remote owner.",
        "tags": [],
        "jsDoc": "/** editor Remote owner. */",
        "key": "editorController",
        "exportName": "EditorController",
        "members": [
          {
            "kind": "method",
            "name": "languageServers",
            "signature": "@Remote async languageServers(request: EditorLanguageServersRequest, signal: AbortSignal): Promise<EditorLanguageServersValue>",
            "summary": "Execute editor.languageServers.",
            "jsDoc": "/** Execute editor.languageServers.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled editor result.\n */"
          },
          {
            "kind": "method",
            "name": "listDir",
            "signature": "@Remote async listDir(request: EditorListDirRequest, signal: AbortSignal): Promise<EditorListDirValue>",
            "summary": "Execute editor.listDir.",
            "jsDoc": "/** Execute editor.listDir.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled editor result.\n */"
          },
          {
            "kind": "method",
            "name": "readFile",
            "signature": "@Remote async readFile(request: EditorReadFileRequest, signal: AbortSignal): Promise<EditorReadFileValue>",
            "summary": "Execute editor.readFile.",
            "jsDoc": "/** Execute editor.readFile.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled editor result.\n */"
          }
        ],
        "types": [
          {
            "name": "EditorDirEntry",
            "declaration": "export interface EditorDirEntry {\n    readonly name: string;\n    readonly path: string;\n    readonly directory: boolean;\n}"
          },
          {
            "name": "EditorFile",
            "declaration": "export interface EditorFile {\n    readonly path: string;\n    readonly content: string;\n    readonly version: string;\n}"
          },
          {
            "name": "EditorLanguageServer",
            "declaration": "export interface EditorLanguageServer {\n    readonly id: string;\n    readonly extensions: readonly string[];\n}"
          },
          {
            "name": "EditorLanguageServersRequest",
            "declaration": "export type EditorLanguageServersRequest = {};"
          },
          {
            "name": "EditorLanguageServersValue",
            "declaration": "export type EditorLanguageServersValue = { servers: readonly EditorLanguageServer[]; };"
          },
          {
            "name": "EditorListDirRequest",
            "declaration": "export type EditorListDirRequest = { sessionId?: SessionId; path?: string; };"
          },
          {
            "name": "EditorListDirValue",
            "declaration": "export type EditorListDirValue = EditorListing;"
          },
          {
            "name": "EditorListing",
            "declaration": "export interface EditorListing {\n    readonly path: string;\n    readonly root: string;\n    readonly entries: readonly EditorDirEntry[];\n}"
          },
          {
            "name": "EditorReadFileRequest",
            "declaration": "export type EditorReadFileRequest = { sessionId?: SessionId; path: string; };"
          },
          {
            "name": "EditorReadFileValue",
            "declaration": "export type EditorReadFileValue = EditorFile;"
          }
        ]
      },
      {
        "description": "treadmill Remote owner.",
        "summary": "treadmill Remote owner.",
        "tags": [],
        "jsDoc": "/** treadmill Remote owner. */",
        "key": "treadmillController",
        "exportName": "TreadmillController",
        "members": [
          {
            "kind": "method",
            "name": "describe",
            "signature": "@Remote async describe(request: TreadmillDescribeRequest, signal: AbortSignal): Promise<TreadmillDescribeValue>",
            "summary": "Execute treadmill.describe.",
            "jsDoc": "/** Execute treadmill.describe.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled treadmill result.\n */"
          },
          {
            "kind": "method",
            "name": "readFile",
            "signature": "@Remote async readFile(request: TreadmillReadFileRequest, signal: AbortSignal): Promise<TreadmillReadFileValue>",
            "summary": "Execute treadmill.readFile.",
            "jsDoc": "/** Execute treadmill.readFile.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled treadmill result.\n */"
          },
          {
            "kind": "method",
            "name": "writeFile",
            "signature": "@Remote async writeFile(request: TreadmillWriteFileRequest, signal: AbortSignal): Promise<TreadmillWriteFileValue>",
            "summary": "Execute treadmill.writeFile.",
            "jsDoc": "/** Execute treadmill.writeFile.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled treadmill result.\n */"
          },
          {
            "kind": "method",
            "name": "updateStage",
            "signature": "@Remote async updateStage(request: TreadmillUpdateStageRequest, signal: AbortSignal): Promise<TreadmillUpdateStageValue>",
            "summary": "Execute treadmill.updateStage.",
            "jsDoc": "/** Execute treadmill.updateStage.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled treadmill result.\n */"
          },
          {
            "kind": "method",
            "name": "saveToProject",
            "signature": "@Remote async saveToProject(request: TreadmillSaveToProjectRequest, signal: AbortSignal): Promise<TreadmillSaveToProjectValue>",
            "summary": "Execute treadmill.saveToProject.",
            "jsDoc": "/** Execute treadmill.saveToProject.\n * @param request - operator parameters.\n * @param signal - caller cancellation.\n * @returns the settled treadmill result.\n */"
          }
        ],
        "types": [
          {
            "name": "TreadmillDescribeRequest",
            "declaration": "export type TreadmillDescribeRequest = { sessionId?: SessionId; };"
          },
          {
            "name": "TreadmillDescribeValue",
            "declaration": "export type TreadmillDescribeValue = TreadmillDescriptionView;"
          },
          {
            "name": "TreadmillDescriptionView",
            "declaration": "export interface TreadmillDescriptionView {\n    readonly root: string;\n    readonly enabled: boolean;\n    readonly tableSource: 'project' | 'global';\n    readonly stages: readonly TreadmillStageView[];\n    readonly pipelineError?: string;\n    readonly files: readonly TreadmillFileView[];\n}"
          },
          {
            "name": "TreadmillFileView",
            "declaration": "export interface TreadmillFileView {\n    readonly path: string;\n    readonly category: string;\n    readonly size: number;\n}"
          },
          {
            "name": "TreadmillReadFileRequest",
            "declaration": "export type TreadmillReadFileRequest = { path: string; };"
          },
          {
            "name": "TreadmillReadFileValue",
            "declaration": "export type TreadmillReadFileValue = { path: string; content: string; };"
          },
          {
            "name": "TreadmillSaveToProjectRequest",
            "declaration": "export type TreadmillSaveToProjectRequest = { sessionId: SessionId; path: string; content: string; };"
          },
          {
            "name": "TreadmillSaveToProjectValue",
            "declaration": "export type TreadmillSaveToProjectValue = { path: string; };"
          },
          {
            "name": "TreadmillStageView",
            "declaration": "export interface TreadmillStageView {\n    readonly requires?: readonly string[];\n    readonly id: string;\n    readonly label: string;\n    readonly section: string;\n    readonly skill: string;\n    readonly args?: string;\n    readonly gate: 'manual' | 'auto';\n    readonly verdict: boolean;\n    readonly produces: readonly string[];\n    readonly enabled: boolean;\n}"
          },
          {
            "name": "TreadmillUpdateStageRequest",
            "declaration": "export type TreadmillUpdateStageRequest = { sessionId?: SessionId; id: string; enabled?: boolean; gate?: 'manual' | 'auto'; };"
          },
          {
            "name": "TreadmillUpdateStageValue",
            "declaration": "export type TreadmillUpdateStageValue = { id: string; tableSource: 'project' | 'global'; };"
          },
          {
            "name": "TreadmillWriteFileRequest",
            "declaration": "export type TreadmillWriteFileRequest = { path: string; content: string; };"
          },
          {
            "name": "TreadmillWriteFileValue",
            "declaration": "export type TreadmillWriteFileValue = { path: string; };"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
