/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { DockerBrowseComposeRequest, DockerBrowseComposeValue, DockerComposeDownRequest, DockerComposeDownValue, DockerComposeUpRequest, DockerComposeUpValue, DockerControlRequest, DockerControlValue, DockerEngineStatusRequest, DockerEngineStatusValue, DockerInstallEngineRequest, DockerInstallEngineValue, DockerListContainersRequest, DockerListContainersValue, DockerListImagesRequest, DockerListImagesValue, DockerLogsRequest, DockerLogsValue, DockerRemoveContainerRequest, DockerRemoveContainerValue, DockerRemoveImageRequest, DockerRemoveImageValue, DockerStartEngineRequest, DockerStartEngineValue, EditorLanguageServersRequest, EditorLanguageServersValue, EditorListDirRequest, EditorListDirValue, EditorReadFileRequest, EditorReadFileValue, TreadmillDescribeRequest, TreadmillDescribeValue, TreadmillReadFileRequest, TreadmillReadFileValue, TreadmillSaveToProjectRequest, TreadmillSaveToProjectValue, TreadmillUpdateStageRequest, TreadmillUpdateStageValue, TreadmillWriteFileRequest, TreadmillWriteFileValue } from '@persike/dsh-project-tools/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$646f636b6572 {
    browseCompose: (request: DockerBrowseComposeRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerBrowseComposeValue>>
    composeDown: (request: DockerComposeDownRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerComposeDownValue>>
    composeUp: (request: DockerComposeUpRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerComposeUpValue>>
    control: (request: DockerControlRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerControlValue>>
    engineStatus: (request: DockerEngineStatusRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerEngineStatusValue>>
    installEngine: (request: DockerInstallEngineRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerInstallEngineValue>>
    listContainers: (request: DockerListContainersRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerListContainersValue>>
    listImages: (request: DockerListImagesRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerListImagesValue>>
    logs: (request: DockerLogsRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerLogsValue>>
    removeContainer: (request: DockerRemoveContainerRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerRemoveContainerValue>>
    removeImage: (request: DockerRemoveImageRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerRemoveImageValue>>
    startEngine: (request: DockerStartEngineRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerStartEngineValue>>
  }
  interface TypertRemoteNamespace$656469746f72 {
    languageServers: (request: EditorLanguageServersRequest, signal?: AbortSignal) => Promise<RemoteResult<EditorLanguageServersValue>>
    listDir: (request: EditorListDirRequest, signal?: AbortSignal) => Promise<RemoteResult<EditorListDirValue>>
    readFile: (request: EditorReadFileRequest, signal?: AbortSignal) => Promise<RemoteResult<EditorReadFileValue>>
  }
  interface TypertRemoteNamespace$74726561646d696c6c {
    describe: (request: TreadmillDescribeRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillDescribeValue>>
    readFile: (request: TreadmillReadFileRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillReadFileValue>>
    saveToProject: (request: TreadmillSaveToProjectRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillSaveToProjectValue>>
    updateStage: (request: TreadmillUpdateStageRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillUpdateStageValue>>
    writeFile: (request: TreadmillWriteFileRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillWriteFileValue>>
  }
  interface TypertRemoteMap {
    'docker/browseCompose': (request: DockerBrowseComposeRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerBrowseComposeValue>>
    'docker/composeDown': (request: DockerComposeDownRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerComposeDownValue>>
    'docker/composeUp': (request: DockerComposeUpRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerComposeUpValue>>
    'docker/control': (request: DockerControlRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerControlValue>>
    'docker/engineStatus': (request: DockerEngineStatusRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerEngineStatusValue>>
    'docker/installEngine': (request: DockerInstallEngineRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerInstallEngineValue>>
    'docker/listContainers': (request: DockerListContainersRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerListContainersValue>>
    'docker/listImages': (request: DockerListImagesRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerListImagesValue>>
    'docker/logs': (request: DockerLogsRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerLogsValue>>
    'docker/removeContainer': (request: DockerRemoveContainerRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerRemoveContainerValue>>
    'docker/removeImage': (request: DockerRemoveImageRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerRemoveImageValue>>
    'docker/startEngine': (request: DockerStartEngineRequest, signal?: AbortSignal) => Promise<RemoteResult<DockerStartEngineValue>>
    'editor/languageServers': (request: EditorLanguageServersRequest, signal?: AbortSignal) => Promise<RemoteResult<EditorLanguageServersValue>>
    'editor/listDir': (request: EditorListDirRequest, signal?: AbortSignal) => Promise<RemoteResult<EditorListDirValue>>
    'editor/readFile': (request: EditorReadFileRequest, signal?: AbortSignal) => Promise<RemoteResult<EditorReadFileValue>>
    'treadmill/describe': (request: TreadmillDescribeRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillDescribeValue>>
    'treadmill/readFile': (request: TreadmillReadFileRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillReadFileValue>>
    'treadmill/saveToProject': (request: TreadmillSaveToProjectRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillSaveToProjectValue>>
    'treadmill/updateStage': (request: TreadmillUpdateStageRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillUpdateStageValue>>
    'treadmill/writeFile': (request: TreadmillWriteFileRequest, signal?: AbortSignal) => Promise<RemoteResult<TreadmillWriteFileValue>>
  }
  interface TypertRemoteNamespaceMap {
    'docker': TypertRemoteNamespace$646f636b6572
    'editor': TypertRemoteNamespace$656469746f72
    'treadmill': TypertRemoteNamespace$74726561646d696c6c
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
